# Generated by Django 3.0.4 on 2024-09-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userPassword',
            new_name='username',
        ),
    ]
