# Generated by Django 3.0.4 on 2024-09-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20240918_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroList',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
