# Generated by Django 3.0.4 on 2024-09-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_herolist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroList',
            new_name='HeroListModel',
        ),
    ]
