# Generated by Django 3.0.4 on 2024-09-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20240919_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herolistmodel',
            name='imageUrl',
            field=models.CharField(max_length=400),
        ),
    ]
