# Generated by Django 3.0.4 on 2024-09-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
