# Generated by Django 3.0.4 on 2024-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_auto_20240926_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileadmin',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
