# Generated by Django 3.0.4 on 2024-09-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_userprofileadmin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spluser',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserProfileAdmin',
        ),
    ]
