# Generated by Django 3.0.4 on 2024-09-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_auto_20240926_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='spluser',
            new_name='is_staff',
        ),
        migrations.DeleteModel(
            name='UserProfileAdmin',
        ),
    ]
