# Generated by Django 3.0.4 on 2024-10-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_auto_20240927_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='herolistmodel',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
